import mdx from "@astrojs/mdx";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";
import vercel from "@astrojs/vercel";
import tailwindcss from "@tailwindcss/vite";
import AutoImport from "astro-auto-import";
import { defineConfig } from "astro/config";
import remarkCollapse from "remark-collapse";
import remarkToc from "remark-toc";
import sharp from "sharp";
import { createClient } from "@sanity/client";
import config from "./src/config/config.json";

// Fetch city slugs from Sanity at build time for sitemap
const sanityBuildClient = createClient({
  projectId: process.env.SANITY_PROJECT_ID || "mi2de5uc",
  dataset: process.env.SANITY_DATASET || "production",
  apiVersion: "2026-03-01",
  useCdn: true,
});

let citySlugs = [];
try {
  citySlugs = await sanityBuildClient.fetch(
    `*[_type == "cityPage"]{ "slug": slug.current }`
  );
} catch (e) {
  console.warn("[sitemap] Failed to fetch city slugs from Sanity:", e.message);
}

let highlighter;
async function getHighlighter() {
  if (!highlighter) {
    const { getHighlighter } = await import("shiki");
    highlighter = await getHighlighter({ theme: "one-dark-pro" });
  }
  return highlighter;
}

// https://astro.build/config
export default defineConfig({
  site: config.site.base_url ? config.site.base_url : "http://examplesite.com",
  base: config.site.base_path ? config.site.base_path : "/",
  trailingSlash: config.site.trailing_slash ? "always" : "never",
  adapter: vercel(),
  redirects: {
    // ── Phoenix (whiteglovecarpet.com) — Legacy WordPress → New Astro ──
    // Service / booking aliases
    "/booknow": "/appointment",
    "/frequently-asked-questions": "/contact",
    "/why-chem-dry": "/about",
    "/chem-dry-vs-steam-cleaning": "/services/carpet-cleaning",
    "/chem-dry-cares": "/about",
    "/accessibility": "/privacy-policy",
    // Service page URL variants
    "/services/tile-cleaning": "/services/tile-and-grout-cleaning",
    "/services/tile-grout-cleaning": "/services/tile-and-grout-cleaning",
    "/services/pet-urine-odor-removal": "/services/pet-urine-removal",
    "/services/stone-cleaning": "/services/stone-tile-cleaning-polishing",
    "/services/granite-renewal": "/services/granite-countertop-renewal",
    "/services/kitchen-tile-cleaning": "/services/tile-and-grout-cleaning",
    "/services/stone-tile-floor-cleaning": "/services/stone-tile-cleaning-polishing",
    // Blog posts — 301 redirects: legacy WP root slugs → /blog/{slug}
    "/5-things-to-look-for-in-a-carpet-cleaning-company": "/blog/5-things-to-look-for-in-a-carpet-cleaning-company",
    "/advantages-of-using-a-fabric-sofa-cleaner": "/blog/advantages-of-using-a-fabric-sofa-cleaner",
    "/affordable-carpet-cleaning": "/blog/affordable-carpet-cleaning",
    "/amazing-solutions-pet-stain-remover": "/blog/amazing-solutions-pet-stain-remover",
    "/antique-rug-cleaning-near-me": "/blog/antique-rug-cleaning-near-me",
    "/antique-rug-cleaning": "/blog/antique-rug-cleaning",
    "/apartment-carpet-cleaning": "/blog/apartment-carpet-cleaning",
    "/are-you-supposed-to-tip-carpet-cleaners": "/blog/are-you-supposed-to-tip-carpet-cleaners",
    "/area-rug-carpet-cleaning-near-me": "/blog/area-rug-carpet-cleaning-near-me",
    "/area-rug-carpet-cleaning-tips": "/blog/area-rug-carpet-cleaning-tips",
    "/area-rug-carpet-cleaning": "/blog/area-rug-carpet-cleaning",
    "/area-rug-cleaning-3": "/blog/area-rug-cleaning-3",
    "/area-rug-cleaning-company": "/blog/area-rug-cleaning-company",
    "/area-rug-cleaning-cost": "/blog/area-rug-cleaning-cost",
    "/area-rug-cleaning-drop-off-near-me": "/blog/area-rug-cleaning-drop-off-near-me",
    "/area-rug-cleaning-drop-off": "/blog/area-rug-cleaning-drop-off",
    "/area-rug-cleaning-near-me": "/blog/area-rug-cleaning-near-me",
    "/area-rug-cleaning-pickup-and-delivery-near-me": "/blog/area-rug-cleaning-pickup-and-delivery-near-me",
    "/area-rug-cleaning-service": "/blog/area-rug-cleaning-service",
    "/area-rug-cleaning-services-near-me": "/blog/area-rug-cleaning-services-near-me",
    "/area-rug-cleaning-why-its-important-and-how-to-do-it-yourself": "/blog/area-rug-cleaning-why-its-important-and-how-to-do-it-yourself",
    "/area-rug-dry-cleaning-near-me": "/blog/area-rug-dry-cleaning-near-me",
    "/area-rug-dry-cleaning": "/blog/area-rug-dry-cleaning",
    "/arizona-commemorative-air-force-museum": "/blog/arizona-commemorative-air-force-museum",
    "/arizona-golf-resort-event-center": "/blog/arizona-golf-resort-event-center",
    "/arrowhead-meadows-park": "/blog/arrowhead-meadows-park",
    "/august-newsletter": "/blog/august-newsletter",
    "/augusta-ranch-golf-club": "/blog/augusta-ranch-golf-club",
    "/bell-bank-park": "/blog/bell-bank-park",
    "/benefits-of-dry-carpet-cleaning": "/blog/benefits-of-dry-carpet-cleaning",
    "/benefits-of-investing-in-a-carpet-cleaner-service": "/blog/benefits-of-investing-in-a-carpet-cleaner-service",
    "/best-area-rug-cleaner": "/blog/best-area-rug-cleaner",
    "/best-carpet-and-upholstery-cleaner": "/blog/best-carpet-and-upholstery-cleaner",
    "/best-carpet-cleaner-machine": "/blog/best-carpet-cleaner-machine",
    "/best-carpet-cleaners-in-my-area": "/blog/best-carpet-cleaners-in-my-area",
    "/best-carpet-cleaners-near-me": "/blog/best-carpet-cleaners-near-me",
    "/best-carpet-cleaning-company-near-me": "/blog/best-carpet-cleaning-company-near-me",
    "/best-carpet-cleaning-company": "/blog/best-carpet-cleaning-company",
    "/best-carpet-steam-cleaner": "/blog/best-carpet-steam-cleaner",
    "/best-deals-on-carpet-cleaners": "/blog/best-deals-on-carpet-cleaners",
    "/best-fabric-sofa-cleaner": "/blog/best-fabric-sofa-cleaner",
    "/best-home-carpet-cleaner": "/blog/best-home-carpet-cleaner",
    "/best-home-carpet-steam-cleaner": "/blog/best-home-carpet-steam-cleaner",
    "/best-home-rug-cleaner": "/blog/best-home-rug-cleaner",
    "/best-oriental-rug-cleaning-near-me": "/blog/best-oriental-rug-cleaning-near-me",
    "/best-pet-stain-and-odor-remover-for-carpet-cleaners": "/blog/best-pet-stain-and-odor-remover-for-carpet-cleaners",
    "/best-pet-stain-and-odor-remover": "/blog/best-pet-stain-and-odor-remover",
    "/best-pet-stain-remover-for-carpets": "/blog/best-pet-stain-remover-for-carpets",
    "/best-pet-vomit-stain-remover": "/blog/best-pet-vomit-stain-remover",
    "/best-rated-carpet-cleaners-near-me": "/blog/best-rated-carpet-cleaners-near-me",
    "/best-rated-vacuum-cleaners-for-carpet": "/blog/best-rated-vacuum-cleaners-for-carpet",
    "/best-rug-cleaner-for-pets": "/blog/best-rug-cleaner-for-pets",
    "/best-rug-cleaner-solution": "/blog/best-rug-cleaner-solution",
    "/best-rug-cleaner": "/blog/best-rug-cleaner",
    "/best-rug-steam-cleaner": "/blog/best-rug-steam-cleaner",
    "/best-sofa-cleaner-machine": "/blog/best-sofa-cleaner-machine",
    "/best-sofa-cleaner": "/blog/best-sofa-cleaner",
    "/best-upholstery-cleaner-for-couch": "/blog/best-upholstery-cleaner-for-couch",
    "/best-upholstery-cleaner": "/blog/best-upholstery-cleaner",
    "/best-upholstery-cleaning-service-near-me": "/blog/best-upholstery-cleaning-service-near-me",
    "/best-upholstery-cleaning-solution": "/blog/best-upholstery-cleaning-solution",
    "/best-upholstery-steam-cleaner": "/blog/best-upholstery-steam-cleaner",
    "/best-vacuum-cleaner-for-carpet": "/blog/best-vacuum-cleaner-for-carpet",
    "/best-way-to-remove-pet-urine-stains-from-carpet": "/blog/best-way-to-remove-pet-urine-stains-from-carpet",
    "/better-carpet-cleaners": "/blog/better-carpet-cleaners",
    "/cactus-yards": "/blog/cactus-yards",
    "/can-you-use-a-carpet-cleaner-on-a-rug": "/blog/can-you-use-a-carpet-cleaner-on-a-rug",
    "/car-carpet-cleaner-machine": "/blog/car-carpet-cleaner-machine",
    "/carpet-and-couch-cleaner": "/blog/carpet-and-couch-cleaner",
    "/carpet-and-floor-cleaners-near-me": "/blog/carpet-and-floor-cleaners-near-me",
    "/carpet-and-furniture-cleaning": "/blog/carpet-and-furniture-cleaning",
    "/carpet-and-rug-cleaners-near-me": "/blog/carpet-and-rug-cleaners-near-me",
    "/carpet-and-rug-cleaners": "/blog/carpet-and-rug-cleaners",
    "/carpet-and-sofa-cleaner": "/blog/carpet-and-sofa-cleaner",
    "/carpet-and-tile-cleaning": "/blog/carpet-and-tile-cleaning",
    "/carpet-and-upholstery-cleaner-near-me-2": "/blog/carpet-and-upholstery-cleaner-near-me-2",
    "/carpet-and-upholstery-cleaner-near-me": "/blog/carpet-and-upholstery-cleaner-near-me",
    "/carpet-and-upholstery-cleaner": "/blog/carpet-and-upholstery-cleaner",
    "/carpet-and-upholstery-steam-cleaner": "/blog/carpet-and-upholstery-steam-cleaner",
    "/carpet-cleaner-extractor": "/blog/carpet-cleaner-extractor",
    "/carpet-cleaner-for-dog-pee": "/blog/carpet-cleaner-for-dog-pee",
    "/carpet-cleaner-for-stairs": "/blog/carpet-cleaner-for-stairs",
    "/carpet-cleaner-liquid": "/blog/carpet-cleaner-liquid",
    "/carpet-cleaner-reviews": "/blog/carpet-cleaner-reviews",
    "/carpet-cleaner-service": "/blog/carpet-cleaner-service",
    "/carpet-cleaner-solution": "/blog/carpet-cleaner-solution",
    "/carpet-cleaner-spray": "/blog/carpet-cleaner-spray",
    "/carpet-cleaner-vacuum": "/blog/carpet-cleaner-vacuum",
    "/carpet-cleaner": "/blog/carpet-cleaner",
    "/carpet-cleaners-in-my-area": "/blog/carpet-cleaners-in-my-area",
    "/carpet-cleaners-in-the-area": "/blog/carpet-cleaners-in-the-area",
    "/carpet-cleaners-near-me-reviews": "/blog/carpet-cleaners-near-me-reviews",
    "/carpet-cleaners-near-my-location": "/blog/carpet-cleaners-near-my-location",
    "/carpet-cleaning-before-and-after": "/blog/carpet-cleaning-before-and-after",
    "/carpet-cleaning-brush": "/blog/carpet-cleaning-brush",
    "/carpet-cleaning-business": "/blog/carpet-cleaning-business",
    "/carpet-cleaning-companies-near-me": "/blog/carpet-cleaning-companies-near-me",
    "/carpet-cleaning-companies": "/blog/carpet-cleaning-companies",
    "/carpet-cleaning-company": "/blog/carpet-cleaning-company",
    "/carpet-cleaning-cost": "/blog/carpet-cleaning-cost",
    "/carpet-cleaning-deals": "/blog/carpet-cleaning-deals",
    "/carpet-cleaning-equipment": "/blog/carpet-cleaning-equipment",
    "/carpet-cleaning-near-me": "/blog/carpet-cleaning-near-me",
    "/carpet-cleaning-prices": "/blog/carpet-cleaning-prices",
    "/carpet-cleaning-products": "/blog/carpet-cleaning-products",
    "/carpet-cleaning-services-near-me": "/blog/carpet-cleaning-services-near-me",
    "/carpet-cleaning-services": "/blog/carpet-cleaning-services",
    "/carpet-cleaning-specials": "/blog/carpet-cleaning-specials",
    "/carpet-cleaning-supplies": "/blog/carpet-cleaning-supplies",
    "/carpet-cleaning-tips": "/blog/carpet-cleaning-tips",
    "/carpet-furniture-cleaners": "/blog/carpet-furniture-cleaners",
    "/carpet-rug-cleaner": "/blog/carpet-rug-cleaner",
    "/carpet-rug-cleaning-solutions": "/blog/carpet-rug-cleaning-solutions",
    "/carpet-spot-cleaner": "/blog/carpet-spot-cleaner",
    "/carpet-steam-cleaning-near-me-2": "/blog/carpet-steam-cleaning-near-me-2",
    "/carpet-steam-cleaning-near-me": "/blog/carpet-steam-cleaning-near-me",
    "/carpet-upholstery-cleaners-near-me": "/blog/carpet-upholstery-cleaners-near-me",
    "/carpet-upholstery-cleaners": "/blog/carpet-upholstery-cleaners",
    "/cheap-carpet-cleaning-near-me": "/blog/cheap-carpet-cleaning-near-me",
    "/chemdry-carpet-cleaning": "/blog/chemdry-carpet-cleaning",
    "/choosing-a-carpet-and-floor-cleaner": "/blog/choosing-a-carpet-and-floor-cleaner",
    "/cleaning-area-rugs-at-home": "/blog/cleaning-area-rugs-at-home",
    "/cleaning-oriental-rugs-near-me": "/blog/cleaning-oriental-rugs-near-me",
    "/cleaning-sofa-cushions": "/blog/cleaning-sofa-cushions",
    "/commercial-carpet-cleaner": "/blog/commercial-carpet-cleaner",
    "/commercial-carpet-cleaning-equipment": "/blog/commercial-carpet-cleaning-equipment",
    "/commercial-carpet-cleaning-machines": "/blog/commercial-carpet-cleaning-machines",
    "/commercial-carpet-steam-cleaner": "/blog/commercial-carpet-steam-cleaner",
    "/commercial-upholstery-cleaner": "/blog/commercial-upholstery-cleaner",
    "/comparing-carpet-cleaners": "/blog/comparing-carpet-cleaners",
    "/cosmo-dog-park": "/blog/cosmo-dog-park",
    "/dalworth-rug-cleaning": "/blog/dalworth-rug-cleaning",
    "/desert-botanical-garden": "/blog/desert-botanical-garden",
    "/desert-breeze-park": "/blog/desert-breeze-park",
    "/desert-trails-bike-park": "/blog/desert-trails-bike-park",
    "/do-carpet-cleaners-move-furniture": "/blog/do-carpet-cleaners-move-furniture",
    "/dobson-ranch-golf-course": "/blog/dobson-ranch-golf-course",
    "/espee-park": "/blog/espee-park",
    "/golfland-sunsplash": "/blog/golfland-sunsplash",
    "/how-much-does-carpet-cleaning-cost": "/blog/how-much-does-carpet-cleaning-cost",
    "/how-to-choose-the-best-dry-carpet-cleaning-company-near-you": "/blog/how-to-choose-the-best-dry-carpet-cleaning-company-near-you",
    "/how-to-choose-the-right-rug-cleaning-service-for-you": "/blog/how-to-choose-the-right-rug-cleaning-service-for-you",
    "/how-to-clean-tile-floors": "/blog/how-to-clean-tile-floors",
    "/how-to-clean-upholstery-with-a-diy-solution": "/blog/how-to-clean-upholstery-with-a-diy-solution",
    "/how-to-clean-upholstery-with-a-dry-cleaner": "/blog/how-to-clean-upholstery-with-a-dry-cleaner",
    "/how-to-find-carpet-cleaning-near-me": "/blog/how-to-find-carpet-cleaning-near-me",
    "/how-to-get-pet-urine-odor-out-of-carpet": "/blog/how-to-get-pet-urine-odor-out-of-carpet",
    "/how-to-get-spots-out-of-your-carpet": "/blog/how-to-get-spots-out-of-your-carpet",
    "/how-to-make-your-own-diy-carpet-cleaner": "/blog/how-to-make-your-own-diy-carpet-cleaner",
    "/how-to-mop-your-tile-floor-without-just-spreading-dirt-around": "/blog/how-to-mop-your-tile-floor-without-just-spreading-dirt-around",
    "/how-to-prepare-for-your-cleaning": "/blog/how-to-prepare-for-your-cleaning",
    "/how-to-remove-coffee-stains-from-carpet": "/blog/how-to-remove-coffee-stains-from-carpet",
    "/kiwanis-park": "/blog/kiwanis-park",
    "/krazy-air-trampoline-park": "/blog/krazy-air-trampoline-park",
    "/lost-dutchman-state-park": "/blog/lost-dutchman-state-park",
    "/mcqueen-park-activity-center": "/blog/mcqueen-park-activity-center",
    "/mesa-amphitheatre": "/blog/mesa-amphitheatre",
    "/phoenix-zoo": "/blog/phoenix-zoo",
    "/phon-d-sutton-recreation-area": "/blog/phon-d-sutton-recreation-area",
    "/professional-carpet-cleaner": "/blog/professional-carpet-cleaner",
    "/prospector-park": "/blog/prospector-park",
    "/quail-run-sports-complex": "/blog/quail-run-sports-complex",
    "/red-mountain-district-park": "/blog/red-mountain-district-park",
    "/red-mountain-park": "/blog/red-mountain-park",
    "/red-mountain-ranch-country-club": "/blog/red-mountain-ranch-country-club",
    "/should-you-tip-your-carpet-cleaner": "/blog/should-you-tip-your-carpet-cleaner",
    "/skyline-park": "/blog/skyline-park",
    "/the-benefits-and-disadvantages-of-deep-carpet-cleaning": "/blog/the-benefits-and-disadvantages-of-deep-carpet-cleaning",
    "/the-benefits-of-using-a-deep-clean-carpet-cleaner": "/blog/the-benefits-of-using-a-deep-clean-carpet-cleaner",
    "/the-benefits-of-using-a-dog-urine-carpet-cleaner": "/blog/the-benefits-of-using-a-dog-urine-carpet-cleaner",
    "/the-benefits-of-using-a-dry-clean-carpet-cleaner": "/blog/the-benefits-of-using-a-dry-clean-carpet-cleaner",
    "/the-best-way-to-clean-your-carpets-on-a-budget": "/blog/the-best-way-to-clean-your-carpets-on-a-budget",
    "/the-importance-of-deep-carpet-cleaning": "/blog/the-importance-of-deep-carpet-cleaning",
    "/tips-for-keeping-your-carpet-clean-with-a-dog": "/blog/tips-for-keeping-your-carpet-clean-with-a-dog",
    "/tips-on-cleaning-carpets-2": "/blog/tips-on-cleaning-carpets-2",
    "/usery-mountain-regional-park": "/blog/usery-mountain-regional-park",
    "/what-is-a-good-carpet-cleaner": "/blog/what-is-a-good-carpet-cleaner",
    "/what-is-best-carpet-cleaner-for-area-rugs": "/blog/what-is-best-carpet-cleaner-for-area-rugs",
    "/what-is-best-carpet-cleaner-for-dog-urine": "/blog/what-is-best-carpet-cleaner-for-dog-urine",
    "/what-is-best-carpet-cleaner-for-pet-stains": "/blog/what-is-best-carpet-cleaner-for-pet-stains",
    "/what-is-best-carpet-cleaner-for-pet-urine": "/blog/what-is-best-carpet-cleaner-for-pet-urine",
    "/what-is-best-carpet-cleaner-for-pets": "/blog/what-is-best-carpet-cleaner-for-pets",
    "/what-is-best-carpet-cleaner-product": "/blog/what-is-best-carpet-cleaner-product",
    "/what-is-best-carpet-cleaner-solution-for-pets": "/blog/what-is-best-carpet-cleaner-solution-for-pets",
    "/what-is-best-carpet-cleaner-solution": "/blog/what-is-best-carpet-cleaner-solution",
    "/what-is-best-carpet-cleaner": "/blog/what-is-best-carpet-cleaner",
    "/what-is-best-leather-sofa-cleaner": "/blog/what-is-best-leather-sofa-cleaner",
    "/what-is-carpet-rug-cleaner": "/blog/what-is-carpet-rug-cleaner",
    "/what-is-carpet-shampoo-cleaner": "/blog/what-is-carpet-shampoo-cleaner",
    "/what-is-carpet-spot-cleaner-machine": "/blog/what-is-carpet-spot-cleaner-machine",
    "/what-is-carpet-steam-cleaner": "/blog/what-is-carpet-steam-cleaner",
    "/what-is-chem-dry-carpet-cleaning": "/blog/what-is-chem-dry-carpet-cleaning",
    "/what-is-enzyme-carpet-cleaner": "/blog/what-is-enzyme-carpet-cleaner",
    "/what-is-the-best-carpet-and-upholstery-cleaner": "/blog/what-is-the-best-carpet-and-upholstery-cleaner",
    "/what-to-expect-from-a-professional-rug-cleaning": "/blog/what-to-expect-from-a-professional-rug-cleaning",
    "/what-to-look-for-in-a-carpet-cleaning-company": "/blog/what-to-look-for-in-a-carpet-cleaning-company",
    "/what-you-need-to-know-about-cat-urine-carpet-cleaner": "/blog/what-you-need-to-know-about-cat-urine-carpet-cleaner",
    "/what-you-need-to-know-before-using-a-dry-carpet-cleaner": "/blog/what-you-need-to-know-before-using-a-dry-carpet-cleaner",
    "/why-carpet-cleaning-is-important": "/blog/why-carpet-cleaning-is-important",
    "/why-hire-a-professional-carpet-cleaner": "/blog/why-hire-a-professional-carpet-cleaner",
    "/why-professional-carpet-cleaning-is-necessary-2": "/blog/why-professional-carpet-cleaning-is-necessary-2",
    "/why-professional-carpet-cleaning-is-necessary": "/blog/why-professional-carpet-cleaning-is-necessary",
    "/why-upholstery-cleaning-is-important": "/blog/why-upholstery-cleaning-is-important",
    "/wind-cave-trail": "/blog/wind-cave-trail",
  },

  image: { service: sharp() },
  vite: { plugins: [tailwindcss()] },
  integrations: [
    react(),
    sitemap({
      customPages: citySlugs.map((c) => `${config.site.base_url}/${c.slug}`),
    }),
    AutoImport({
      imports: [
        "@/shortcodes/Button",
        "@/shortcodes/Accordion",
        "@/shortcodes/Notice",
        "@/shortcodes/Video",
        "@/shortcodes/Youtube",
        "@/shortcodes/Tabs",
        "@/shortcodes/Tab",
      ],
    }),
    mdx(),
  ],
  markdown: {
    remarkPlugins: [
      remarkToc,
      [
        remarkCollapse,
        {
          test: "Table of contents",
        },
      ],
    ],
    shikiConfig: {
      theme: "one-dark-pro",
      wrap: true,
    },
    extendDefaultPlugins: true,
    highlighter: getHighlighter,
  },
});
